### Registering a user:

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Max",
    "name": "Max Mustermann",
    "password": "password"
}

### Login:

POST http://localhost:3001/api/login
Content-Type: application/json

{
	"username": "Max",
	"password": "password"
}

### Role update (admin only)

PUT http://localhost:3001/api/users/61e062c4b31230f2c66bcf48
Content-Type: application/json

{
	"role": "admin"
}
